### ISSUE TITLE
https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#12]

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- created pull request `235` for https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pulls
