### ISSUE TITLE
https://github.com/StackExchange/blackbox and more

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#16]
https://github.com/StackExchange/StackExchange.Redis
https://github.com/kevin-montrose/Jil

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/StackExchange/blackbox received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/StackExchange/StackExchange.Redis received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/kevin-montrose/Jil received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run complete for 3 repos
