### ISSUE TITLE
https://github.com/clojure/core.async

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#17]
https://github.com/FFmpeg/FFmpeg
https://github.com/google/grafika

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/clojure/core.async received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/FFmpeg/FFmpeg received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/google/grafika received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 3 repos
