### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#18]
https://github.com/Sdogruyol/awesome-ruby
https://github.com/markets/awesome-ruby

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Sdogruyol/awesome-ruby received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/markets/awesome-ruby received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos 
- created pull request `60` for https://github.com/sdogruyol/awesome-ruby/pulls
