### ISSUE TITLE
test

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#19]
https://github.com/thellimist/EZAlertController
https://github.com/goktugyil/EZSwiftExtensions

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/thellimist/EZAlertController received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/goktugyil/EZSwiftExtensions received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos
