### ISSUE TITLE
https://github.com/lmenezes/elasticsearch-kopf

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#21]

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/lmenezes/elasticsearch-kopf received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `lmenezes/elasticsearch-kopf`: https://gist.github.com/9f3dc7a9e41683fb5c87
