### ISSUE TITLE
https://github.com/paulmillr/chokidar

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#22]
https://github.com/paulmillr/exoskeleton

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/paulmillr/chokidar received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/paulmillr/exoskeleton received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos 
- Results for `paulmillr/chokidar`: https://gist.github.com/92fd942ee389954cd365 
- Results for `paulmillr/exoskeleton`: https://gist.github.com/429aea5e161332727c99
