### ISSUE TITLE
https://github.com/segmentio/metalsmith

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#23]
https://github.com/segmentio/nightmare

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/segmentio/metalsmith received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/segmentio/nightmare received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos 
- Results for `segmentio/metalsmith`: https://gist.github.com/270acb78f195287086cd 
- Results for `segmentio/nightmare`: https://gist.github.com/7b3bdbf7769c18e136f6
