### ISSUE TITLE
https://github.com/draios/sysdig

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#26]

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/draios/sysdig received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `draios/sysdig`: https://gist.github.com/cef0bcd35fcca606e65f 
- Created pull request `481` for https://github.com/draios/sysdig/pulls
