### ISSUE TITLE
reem

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#27]
https://github.com/iron/persistent
https://github.com/hyperium/hyper

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/iron/persistent received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/hyperium/hyper received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos 
- Results for `iron/persistent`: https://gist.github.com/a70959951130f8ab6ea3 
- Results for `hyperium/hyper`: https://gist.github.com/79a0a4caf2ec5d6c532a
