### ISSUE TITLE
stefanjudis

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#28]
https://github.com/stefanjudis/perf-tooling
https://github.com/loopline-systems/electron-builder

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/stefanjudis/perf-tooling received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/loopline-systems/electron-builder received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos 
- Results for `stefanjudis/perf-tooling`: https://gist.github.com/4003d89dcf3d68eebe8a 
- Results for `loopline-systems/electron-builder`: https://gist.github.com/d30a6cd1a3359abe3b92
