### ISSUE TITLE
elm

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#29]
https://github.com/elm-lang/elm-platform
https://github.com/elm-lang/elm-compiler
https://github.com/elm-lang/elm-lang.org

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/elm-lang/elm-platform received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/elm-lang/elm-compiler received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/elm-lang/elm-lang.org received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 3 repos 
- Results for `elm-lang/elm-platform`: https://gist.github.com/10c558496d120e0a2467 
- Results for `elm-lang/elm-compiler`: https://gist.github.com/a80303d6fa1f2363d4b6 
- Results for `elm-lang/elm-lang.org`: https://gist.github.com/e8c545293def9ad0e1fe
