### ISSUE TITLE
:smile:

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#3]
https://github.com/zeke/ghwd
https://github.com/zeke/package-json-to-readme
https://github.com/npm/marky-markdown
https://github.com/maxogden/art-of-node

**Comment by ReadmeCritic** [comment]
Issue processed, add to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, add to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, add to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, add to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, add to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, add to `todo`

**Comment by ReadmeCritic** [comment]
`frankenstein` run complete
