### ISSUE TITLE
akamud

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#30]
https://github.com/code-cracker/code-cracker
https://github.com/madskristensen/WebEssentials2015
https://github.com/code-cracker/code-cracker
https://github.com/JeremySkinner/FluentValidation

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/code-cracker/code-cracker received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/madskristensen/WebEssentials2015 received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/JeremySkinner/FluentValidation received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 3 repos 
- Results for `code-cracker/code-cracker`: https://gist.github.com/74aa15df34163155cb85 
- Results for `madskristensen/WebEssentials2015`: https://gist.github.com/d82eec7ac94f23cd05a1 
- Results for `JeremySkinner/FluentValidation`: https://gist.github.com/1857c3c3a4b3802cee41
