### ISSUE TITLE
https://github.com/stylelint/stylelint

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#32]
https://github.com/mathiasbynens/jquery-placeholder

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/stylelint/stylelint received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/mathiasbynens/jquery-placeholder received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos 
- Results for `stylelint/stylelint`: https://gist.github.com/82a08dd51c6498e5f6f3 
- Results for `mathiasbynens/jquery-placeholder`: https://gist.github.com/f40d078ecd6114eb4a21
