### ISSUE TITLE
https://github.com/AliSoftware/SwiftGen

### ISSUE THREAD

**Issue by esttorhe** [ReadmeCritic/Run#33]
https://github.com/AliSoftware/SwiftGen

CC: @AliSoftware

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/AliSoftware/SwiftGen received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `AliSoftware/SwiftGen`: https://gist.github.com/c06f7b9947d648492054
