### ISSUE TITLE
https://github.com/CyberAgent/boombox.js

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#34]
https://github.com/kdabir/awesome-groovy
https://github.com/google/google-api-javascript-client
https://github.com/Starcounter-Jack/JSON-Patch
https://github.com/codegangsta/negroni
https://github.com/h2o/h2o
https://github.com/NarrativeScience/Log.io

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/CyberAgent/boombox.js received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/kdabir/awesome-groovy received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/google/google-api-javascript-client received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Starcounter-Jack/JSON-Patch received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/codegangsta/negroni received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/h2o/h2o received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/NarrativeScience/Log.io received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 7 repos 
- Results for `CyberAgent/boombox.js`: https://gist.github.com/697399d91d27a73f1e96 
- Results for `kdabir/awesome-groovy`: https://gist.github.com/c9300c6ce966f0edac19 
- Results for `google/google-api-javascript-client`: https://gist.github.com/61ecf273af1dcff60be4 
- Results for `Starcounter-Jack/JSON-Patch`: https://gist.github.com/cfd86f1ffc308efb069f 
- Results for `codegangsta/negroni`: https://gist.github.com/4e4a08914352d2f9da97 
- Results for `h2o/h2o`: https://gist.github.com/94cddd2a5572ff53ba65 
- Results for `NarrativeScience/Log.io`: https://gist.github.com/2bc8a5660f380ee2b828 
- Created pull request `103` for https://github.com/codegangsta/negroni/pulls
