### ISSUE TITLE
https://github.com/linnovate/mean

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#35]
https://github.com/Starcounter-Jack/JSON-Patch
https://github.com/google/google-api-nodejs-client
https://github.com/dblock/ruby-enum

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/linnovate/mean received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Starcounter-Jack/JSON-Patch received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/google/google-api-nodejs-client received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/dblock/ruby-enum received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/linnovate/mean received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Starcounter-Jack/JSON-Patch received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/google/google-api-nodejs-client received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/dblock/ruby-enum received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 4 repos 
- Results for `linnovate/mean`: https://gist.github.com/08b0f74dc58dd46ba8d6 
- Results for `Starcounter-Jack/JSON-Patch`: https://gist.github.com/efbc1a3cbe57ea49ac68 
- Results for `google/google-api-nodejs-client`: https://gist.github.com/147cb19ad451dca2feb7 
- Results for `dblock/ruby-enum`: https://gist.github.com/de3fe16212b752aed65f 
- Created pull request `1401` for https://github.com/linnovate/mean/pulls 
- Created pull request `492` for https://github.com/google/google-api-nodejs-client/pulls
