### ISSUE TITLE
Friday

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#36]
https://github.com/oliver-moran/jimp
https://github.com/vlucas/phpdotenv
https://github.com/hwi/HWIOAuthBundle
https://github.com/sjparkinson/static-review
https://github.com/nokonoko/Pomf
https://github.com/schmittjoh/serializer
https://github.com/sequelize/sequelize
https://github.com/caesar0301/awesome-public-datasets
https://github.com/petkaantonov/bluebird
https://github.com/anselmh/object-fit
https://github.com/oliver-moran/jimp
https://github.com/Turistforeningen/node-s3-uploader
https://github.com/robotframework/Selenium2Library
https://github.com/giakki/uncss
https://github.com/Semantic-Org/Semantic-UI
https://github.com/nvzqz/FileKit
https://github.com/krzyzanowskim/Natalie

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/oliver-moran/jimp received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/vlucas/phpdotenv received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/hwi/HWIOAuthBundle received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/sjparkinson/static-review received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/nokonoko/Pomf received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/schmittjoh/serializer received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/sequelize/sequelize received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/caesar0301/awesome-public-datasets received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/petkaantonov/bluebird received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/anselmh/object-fit received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Turistforeningen/node-s3-uploader received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/robotframework/Selenium2Library received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/giakki/uncss received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Semantic-Org/Semantic-UI received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/nvzqz/FileKit received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/krzyzanowskim/Natalie received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 16 repos 
- Results for `oliver-moran/jimp`: https://gist.github.com/f89bb792e82ddddf3f93 
- Results for `vlucas/phpdotenv`: https://gist.github.com/cbf27240802c8d587423 
- Results for `hwi/HWIOAuthBundle`: https://gist.github.com/c1134886f95d914dfdef 
- Results for `sjparkinson/static-review`: https://gist.github.com/428621fb09e755c6c8a0 
- Results for `nokonoko/Pomf`: https://gist.github.com/735d39cac7dfc8457a5c 
- Results for `schmittjoh/serializer`: https://gist.github.com/f15874522a527ac8e0f4 
- Results for `sequelize/sequelize`: https://gist.github.com/a7523a7339d745e22941 
- Results for `caesar0301/awesome-public-datasets`: https://gist.github.com/263e1b7146386abc7dda 
- Results for `petkaantonov/bluebird`: https://gist.github.com/4714d85ea725f9b8438a 
- Results for `anselmh/object-fit`: https://gist.github.com/969f332daae1c150a643 
- Results for `Turistforeningen/node-s3-uploader`: https://gist.github.com/93608fc80f275f0b19e8 
- Results for `robotframework/Selenium2Library`: https://gist.github.com/3a153257bd64dfd4b65d 
- Results for `giakki/uncss`: https://gist.github.com/a27db062c835b5ddb315 
- Results for `Semantic-Org/Semantic-UI`: https://gist.github.com/0c62cb9c8b8788906007 
- Results for `nvzqz/FileKit`: https://gist.github.com/25ca40905f7aaf82aeb0 
- Results for `krzyzanowskim/Natalie`: https://gist.github.com/419b13b0b8e0104ef572 
- Created pull request `539` for https://github.com/robotframework/Selenium2Library/pulls
