### ISSUE TITLE
https://github.com/legomushroom/mojs

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#38]
https://github.com/MostlyAdequate/mostly-adequate-guide
https://github.com/nolimits4web/Swiper
https://github.com/algolia/instantsearch.js
https://github.com/jsdelivr/jsdelivr
https://github.com/legomushroom/iconmelon

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/legomushroom/mojs received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/MostlyAdequate/mostly-adequate-guide received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/nolimits4web/Swiper received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/algolia/instantsearch.js received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/jsdelivr/jsdelivr received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/legomushroom/iconmelon received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 6 repos 
- Results for `legomushroom/mojs`: https://gist.github.com/db9c4f16100f532d3df1 
- Results for `MostlyAdequate/mostly-adequate-guide`: https://gist.github.com/7734eeb77d2d56622b01 
- Results for `nolimits4web/Swiper`: https://gist.github.com/54a8ae036e25d838b3bc 
- Results for `algolia/instantsearch.js`: https://gist.github.com/21eb1cf0552c201ac395 
- Results for `jsdelivr/jsdelivr`: https://gist.github.com/982fd8547ea6d3980d2b 
- Results for `legomushroom/iconmelon`: https://gist.github.com/c2e7107fcfc556a7d47e
