### ISSUE TITLE
https://github.com/banago/PHPloy

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#39]
https://github.com/huandu/facebook

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/banago/PHPloy received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/huandu/facebook received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos 
- Results for `banago/PHPloy`: https://gist.github.com/5844e855a9d261d8fc77 
- Results for `huandu/facebook`: https://gist.github.com/cf47216c70208e5140b9
