### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#4]
https://github.com/Netflix/ice
https://github.com/Masterminds/glide
https://github.com/ukupat/trolol
https://github.com/justjavac/free-programming-books-zh_CN
https://github.com/gjtorikian/html-proofer
https://github.com/gjtorikian/markdowntutorial.com
https://github.com/github/developer.github.com
https://github.com/github/linguist
https://github.com/sparkle-project/Sparkle

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/Netflix/ice to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/Masterminds/glide to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/ukupat/trolol to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/justjavac/free-programming-books-zh_CN to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/gjtorikian/html-proofer to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/gjtorikian/markdowntutorial.com to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/github/developer.github.com to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/github/linguist to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/sparkle-project/Sparkle to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/Netflix/ice to `todo`

**Comment by ReadmeCritic** [comment]
`frankenstein` run complete 

- created pull request for https://github.com/justjavac/free-programming-books-zh_CN/pulls `411`
