### ISSUE TITLE
https://github.com/WalnutiQ/wAlnut

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#40]

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/WalnutiQ/wAlnut received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `WalnutiQ/wAlnut`: https://gist.github.com/b25f0a5e7c5905582172 
- Created pull request `220` for https://github.com/WalnutiQ/wAlnut/pulls
