### ISSUE TITLE
narkoz/guides

### ISSUE THREAD

**Issue by NARKOZ** [ReadmeCritic/Run#42]

**Comment by ReadmeCritic** [comment]
Run request for narkoz/guides received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `narkoz/guides`: https://gist.github.com/1a7ed2cfc17bf5d958b8 
- Created pull request `18` for https://github.com/NARKOZ/guides/pulls
