### ISSUE TITLE
sunday evening

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#47]
https://github.com/openpgpjs/openpgpjs
https://github.com/cmderdev/cmder
https://github.com/mrdoob/three.js/
https://github.com/dhowe/AdNauseam
https://github.com/hexojs/hexo

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/openpgpjs/openpgpjs received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/cmderdev/cmder received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/mrdoob/three.js/ received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/dhowe/AdNauseam received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/hexojs/hexo received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 5 repos 
- Results for `openpgpjs/openpgpjs`: https://gist.github.com/42a954546a6b4c89c224 
- Results for `cmderdev/cmder`: https://gist.github.com/0ddafb90988525c1e166 
- Results for `mrdoob/three.js`: https://gist.github.com/5d7d1e75237ef219ff49 
- Results for `dhowe/AdNauseam`: https://gist.github.com/b2119463d14b1e4cbf34 
- Results for `hexojs/hexo`: https://gist.github.com/dd166078d5fd12c2da13 
- Created pull request `373` for https://github.com/openpgpjs/openpgpjs/pulls
