### ISSUE TITLE
https://github.com/gitlabhq/gitlabhq

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#48]
https://github.com/jneen/rouge
https://github.com/twitter/activerecord-reputation-system

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/gitlabhq/gitlabhq received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/jneen/rouge received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/twitter/activerecord-reputation-system received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 3 repos 
- Results for `gitlabhq/gitlabhq`: https://gist.github.com/4375dd1eb0e7c8fafb92 
- Results for `jneen/rouge`: https://gist.github.com/153144c839dd1e6e9754 
- Results for `twitter/activerecord-reputation-system`: https://gist.github.com/7d3fdebdc584fa92cacf
