### ISSUE TITLE
rbenv/ruby-build

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#49]

**Comment by ReadmeCritic** [comment]
Run request for rbenv/ruby-build received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `rbenv/ruby-build`: https://gist.github.com/2495675bf283b7513d71 
- Created pull request `835` for https://github.com/rbenv/ruby-build/pulls
