### ISSUE TITLE
😁

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#5]
https://github.com/autumnai/leaf
https://github.com/twitter-fabric/velocity-react
https://github.com/esdoc/esdoc
https://github.com/rackt/react-router
https://github.com/rackt/redux-router
https://github.com/chriso/validator.js
https://github.com/chriso/node.io
https://github.com/pypa/pip

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/autumnai/leaf to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/twitter-fabric/velocity-react to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/esdoc/esdoc to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/rackt/react-router to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/rackt/redux-router to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/chriso/validator.js to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/chriso/node.io to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/pypa/pip to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/autumnai/leaf to `todo`

**Comment by ReadmeCritic** [comment]
`frankenstein` run complete for 9 repos 
- created pull request for https://github.com/chriso/node.io/pulls `165`
