### ISSUE TITLE
https://github.com/FH-Potsdam/steel-ant-input-output

### ISSUE THREAD

**Issue by fabiantheblind** [ReadmeCritic/Run#52]

**Comment by fabiantheblind** [comment]
https://github.com/FH-Potsdam/steel-ant-input-output

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/FH-Potsdam/steel-ant-input-output received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `FH-Potsdam/steel-ant-input-output`: https://gist.github.com/016deddde5ddd0e50fa3 
- Created pull request `197` for https://github.com/FH-Potsdam/steel-ant-input-output/pulls
