### ISSUE TITLE
Repo URL Check

### ISSUE THREAD

**Issue by Maikuolan** [ReadmeCritic/Run#54]
https://github.com/Maikuolan/phpMussel
https://github.com/Maikuolan/phpMussel-extras
https://github.com/DanielRuf/phpMussel-themes
https://github.com/Maikuolan/phpMussel-plugin-boilerplate
https://github.com/Maikuolan/phpMussel-plugin-notifications
https://github.com/jasonhinkle/php-gpg
https://github.com/Maikuolan/SFS-Mass-IP-Checker
https://github.com/Maikuolan/zbb-badip-fork

**Comment by dkhamsing** [comment]
[test]

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Maikuolan/phpMussel received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Maikuolan/phpMussel-extras received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/DanielRuf/phpMussel-themes received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Maikuolan/phpMussel-plugin-boilerplate received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Maikuolan/phpMussel-plugin-notifications received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/jasonhinkle/php-gpg received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Maikuolan/SFS-Mass-IP-Checker received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Maikuolan/zbb-badip-fork received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 8 repos 
- Results for `Maikuolan/phpMussel`: https://gist.github.com/d8b32b3d8a41a5c9a4f4 
- Results for `Maikuolan/phpMussel`: https://gist.github.com/7b714d3381b71d806b7a 
- Results for `Maikuolan/phpMussel-extras`: https://gist.github.com/c6b9c3a9158b45fb268f 
- Results for `DanielRuf/phpMussel-themes`: https://gist.github.com/e925e0ad43fcc6900495 
- Results for `Maikuolan/phpMussel`: https://gist.github.com/b2b00bd9cd9d007064e8 
- Results for `Maikuolan/phpMussel-plugin-boilerplate`: https://gist.github.com/aa21eab2f44eef160d3c 
- Results for `Maikuolan/phpMussel`: https://gist.github.com/8e36a86af8f1040e77d2 
- Results for `Maikuolan/phpMussel-plugin-notifications`: https://gist.github.com/0a8c319211493b5eb27e 
- Results for `jasonhinkle/php-gpg`: https://gist.github.com/11369c1cf9a4a9d26ca2 
- Results for `Maikuolan/SFS-Mass-IP-Checker`: https://gist.github.com/902e3182fa829a0ddffc 
- Results for `Maikuolan/zbb-badip-fork`: https://gist.github.com/b4981fb86ddcd82d0176
