### ISSUE TITLE
rshipp/awesome-malware-analysis

### ISSUE THREAD

**Issue by rshipp** [ReadmeCritic/Run#55]

**Comment by rshipp** [comment]
@dkhamsing is it alive?

**Comment by ReadmeCritic** [comment]
Run request for rshipp/awesome-malware-analysis received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `rshipp/awesome-malware-analysis`: https://gist.github.com/4f487f6c751f59e19f57 
- Created pull request `29` for https://github.com/rshipp/awesome-malware-analysis/pulls
