### ISSUE TITLE
tedyoung/awesome-java8

### ISSUE THREAD

**Issue by tedyoung** [ReadmeCritic/Run#56]

**Comment by dkhamsing** [comment]
[process]

**Comment by ReadmeCritic** [comment]
Run request for tedyoung/awesome-java8 received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `tedyoung/awesome-java8`: https://gist.github.com/8a14a9a5a9d0cc4696d8 
- Created pull request `4` for https://github.com/tedyoung/awesome-java8/pulls
