### ISSUE TITLE
https://github.com/scaleway/scaleway-cli

### ISSUE THREAD

**Issue by moul** [ReadmeCritic/Run#57]

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/scaleway/scaleway-cli received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `scaleway/scaleway-cli`: https://gist.github.com/b5537b73639470e67cc2 
- Created pull request `264` for https://github.com/scaleway/scaleway-cli/pulls
