### ISSUE TITLE
moul/advanced-ssh-config

### ISSUE THREAD

**Issue by moul** [ReadmeCritic/Run#58]

**Comment by ReadmeCritic** [comment]
Run request for moul/advanced-ssh-config received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `moul/advanced-ssh-config`: https://gist.github.com/6aa665fb2084416bf93e 
- Created pull request `98` for https://github.com/moul/advanced-ssh-config/pulls
