### ISSUE TITLE
moul/awesome-ssh

### ISSUE THREAD

**Issue by moul** [ReadmeCritic/Run#59]

**Comment by ReadmeCritic** [comment]
Run request for moul/awesome-ssh received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `moul/awesome-ssh`: https://gist.github.com/b2b5fd291da52a63e3e6 
- Created pull request `5` for https://github.com/moul/awesome-ssh/pulls
