### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#6]
https://github.com/request/request
https://github.com/cheeriojs/cheerio

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/request/request to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/cheeriojs/cheerio to `todo`

**Comment by ReadmeCritic** [comment]
Issue processed, added https://github.com/request/request to `todo`

**Comment by ReadmeCritic** [comment]
`frankenstein` run complete for 2 repos 
- created pull request for https://github.com/request/request/pulls `1906`
