### ISSUE TITLE
bearded/ruby-ldap

### ISSUE THREAD

**Issue by bearded** [ReadmeCritic/Run#62]

**Comment by ReadmeCritic** [comment]
Run request for bearded/ruby-ldap received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `bearded/ruby-ldap`: https://gist.github.com/f16d262845c4da54a2b0 
- Created pull request `34` for https://github.com/bearded/ruby-ldap/pulls
