### ISSUE TITLE
duckduckgo/duckduckhack-docs

### ISSUE THREAD

**Issue by GuiltyDolphin** [ReadmeCritic/Run#63]
https://github.com/duckduckgo/duckduckhack-docs

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/duckduckgo/duckduckhack-docs received.

**Comment by ReadmeCritic** [comment]
Run request for duckduckgo/duckduckhack-docs received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 2 repos 
- Results for `duckduckgo/duckduckhack-docs`: https://gist.github.com/a9d58c6bf968a68198b5 
- Results for `duckduckgo/duckduckhack-docs`: https://gist.github.com/3ce1663a2018a932f795
