### ISSUE TITLE
laedit

### ISSUE THREAD

**Issue by laedit** [ReadmeCritic/Run#64]
laedit/vika
laedit/semanticreleasenotesparser

**Comment by ReadmeCritic** [comment]
`frankenstein` run completed for 1 repo 
- Results for `laedit/vika`: https://gist.github.com/36946ee778ebaae263d8 
- Created pull request `20` for https://github.com/laedit/vika/pulls

**Comment by laedit** [comment]
Thanks a lot, this is awesome! :smiley:
