### ISSUE TITLE
7:56pm

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#8]
ReadmeCritic/Run
https://github.com/rackt/reselect
https://github.com/tute/Thumbnail-component-for-CakePHP
https://github.com/mesosphere/chaos
https://github.com/omcljs/ambly

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/rackt/reselect received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/tute/Thumbnail-component-for-CakePHP received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/mesosphere/chaos received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/omcljs/ambly received.

**Comment by ReadmeCritic** [comment]
Run request for ReadmeCritic/Run received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run complete for 5 repos 
- created pull request for https://github.com/mesosphere/chaos/pulls `50`
