### ISSUE TITLE
Tuesday

### ISSUE THREAD

**Issue by dkhamsing** [ReadmeCritic/Run#9]
https://github.com/futurice/android-best-practices
https://github.com/docker/dockercraft
https://github.com/andyiac/githot
https://github.com/princejwesley/Mancy
https://github.com/JStumpp/awesome-android
https://github.com/Reactive-Extensions/RxJS
https://github.com/xgrommx/awesome-redux
https://github.com/gabrielbull/react-desktop
https://github.com/chentsulin/awesome-graphql
https://github.com/thii/FontAwesome.swift
https://github.com/thii/SwiftColors
https://github.com/goktugyil/EZSwiftExtensions
https://github.com/PhamBaTho/BTNavigationDropdownMenu
https://github.com/thellimist/EZPods
https://github.com/thellimist/SwiftRandom
https://github.com/venmo/DVR
https://github.com/nanopack/yoke
https://github.com/dropbox/pyston
https://github.com/MatthewYork/DateTools
https://github.com/dropbox/changes
https://github.com/chentsulin/electron-react-boilerplate
https://github.com/dropbox/djinni
https://github.com/dropbox/SwiftyDropbox
https://github.com/yackle/CLImageEditor
https://github.com/owensd/json-swift
https://github.com/netguru/ngrvalidator

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/futurice/android-best-practices received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/docker/dockercraft received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/andyiac/githot received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/princejwesley/Mancy received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/JStumpp/awesome-android received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/Reactive-Extensions/RxJS received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/xgrommx/awesome-redux received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/gabrielbull/react-desktop received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/chentsulin/awesome-graphql received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/thii/FontAwesome.swift received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/thii/SwiftColors received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/goktugyil/EZSwiftExtensions received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/PhamBaTho/BTNavigationDropdownMenu received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/thellimist/EZPods received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/thellimist/SwiftRandom received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/venmo/DVR received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/nanopack/yoke received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/dropbox/pyston received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/MatthewYork/DateTools received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/dropbox/changes received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/chentsulin/electron-react-boilerplate received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/dropbox/djinni received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/dropbox/SwiftyDropbox received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/yackle/CLImageEditor received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/owensd/json-swift received.

**Comment by ReadmeCritic** [comment]
Run request for https://github.com/netguru/ngrvalidator received.

**Comment by ReadmeCritic** [comment]
`frankenstein` run complete for 26 repos 
- created pull request for https://github.com/futurice/android-best-practices/pulls `86` 
- created pull request for https://github.com/xgrommx/awesome-redux/pulls `97` 
- created pull request for https://github.com/chentsulin/awesome-graphql/pulls `22`
